version: '3.7'
services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: apostinha
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  api:
    build: .
    restart: always
    container_name: api
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
